"use client";

const DATA = {
  results: [
    {
      ticker: "A",
      name: "Agilent Technologies Inc.",
      market: "stocks",
      locale: "us",
      primary_exchange: "XNYS",
      type: "CS",
      active: true,
      currency_name: "usd",
      cik: "0001090872",
      composite_figi: "BBG000C2V3D6",
      share_class_figi: "BBG001SCTQY4",
      last_updated_utc: "2024-05-17T00:00:00Z",
    },
    {
      ticker: "AA",
      name: "Alcoa Corporation",
      market: "stocks",
      locale: "us",
      primary_exchange: "XNYS",
      type: "CS",
      active: true,
      currency_name: "usd",
      cik: "0001675149",
      composite_figi: "BBG00B3T3HD3",
      share_class_figi: "BBG00B3T3HF1",
      last_updated_utc: "2024-07-12T00:00:00Z",
    },
    {
      ticker: "AAA",
      name: "Alternative Access First Priority CLO Bond ETF",
      market: "stocks",
      locale: "us",
      primary_exchange: "ARCX",
      type: "ETF",
      active: true,
      currency_name: "usd",
      composite_figi: "BBG01B0JRCS6",
      share_class_figi: "BBG01B0JRCT5",
      last_updated_utc: "2024-07-12T00:00:00Z",
    },
    {
      ticker: "AAAIF",
      name: "ALTERNATIVE INVSTMENT TR",
      market: "otc",
      locale: "us",
      type: "FUND",
      active: true,
      currency_name: "USD",
      last_updated_utc: "2022-08-26T05:00:07.114Z",
    },
    {
      ticker: "AAALY",
      name: "AAREAL BANK AG UNSP/ADR",
      market: "otc",
      locale: "us",
      type: "ADRC",
      active: true,
      currency_name: "USD",
      composite_figi: "BBG002628DF1",
      share_class_figi: "BBG002628F57",
      last_updated_utc: "2023-05-04T05:00:29.876Z",
    },
    {
      ticker: "AAAU",
      name: "Goldman Sachs Physical Gold ETF Shares",
      market: "stocks",
      locale: "us",
      primary_exchange: "BATS",
      type: "ETF",
      active: true,
      currency_name: "usd",
      cik: "0001708646",
      composite_figi: "BBG00LPXX872",
      share_class_figi: "BBG00LPXX8Z1",
      last_updated_utc: "2024-07-12T00:00:00Z",
    },
    {
      ticker: "AABB",
      name: "ASIA BROADBAND INC",
      market: "otc",
      locale: "us",
      type: "CS",
      active: true,
      currency_name: "USD",
      composite_figi: "BBG000CWNRN5",
      share_class_figi: "BBG001SGRBK5",
      last_updated_utc: "2024-02-13T09:45:11.736Z",
    },
    {
      ticker: "AABKF",
      name: "AAREAL BANK AG",
      market: "otc",
      locale: "us",
      type: "OS",
      active: true,
      currency_name: "USD",
      last_updated_utc: "2024-06-24T06:45:59.311Z",
    },
    {
      ticker: "AABVF",
      name: "ABERDEEN INTL INC",
      market: "otc",
      locale: "us",
      type: "OS",
      active: true,
      currency_name: "USD",
      composite_figi: "BBG000BXKHJ4",
      share_class_figi: "BBG001S6XZ90",
      last_updated_utc: "2023-05-10T05:00:36.305Z",
    },
    {
      ticker: "AACAF",
      name: "AAC TECHS HLDGS INC ORD",
      market: "otc",
      locale: "us",
      type: "OS",
      active: true,
      currency_name: "USD",
      last_updated_utc: "2022-06-24T14:14:05.429Z",
    },
  ],
  status: "OK",
  request_id: "ec4a67ce1956158a8492ff5f3c93e837",
  count: 10,
  next_url:
    "https://api.polygon.io/v3/reference/tickers?cursor=YWN0aXZlPXRydWUmYXA9QUFDQUYlN0NiZGQ2MGZkZjBiNjk2OGViMTQxNDM5OTFmZDRlYTA3Mzc4NmIwYjIxZDBlOGIwNzNmZjQwZGI4YTBlYzkwNmM5JmFzPSZkYXRlPTIwMjQtMDctMTUmbGltaXQ9MTAmb3JkZXI9YXNjJnNvcnQ9dGlja2Vy",
};

export default function StockData({ params }: { params: { slug: string } }) {
  const stock = DATA.results.filter((obj) => obj.ticker === params.slug);

  return <div>{stock[0].name}</div>;
}
